// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Case struct {
	ID              string            `json:"id"`
	PacienteID      string            `json:"pacienteId"`
	PacienteNombre  string            `json:"pacienteNombre"`
	PacienteEmail   string            `json:"pacienteEmail"`
	FechaSubida     string            `json:"fechaSubida"`
	Estado          string            `json:"estado"`
	URLRadiografia  string            `json:"urlRadiografia"`
	Resultados      *ResultadosModelo `json:"resultados"`
	DoctorAsignado  *string           `json:"doctorAsignado"`
}

type PreDiagnostic struct {
	PrediagnosticID  string            `json:"prediagnostic_id"`
	PacienteID       string            `json:"pacienteId"`
	Urlrad           string            `json:"urlrad"`
	Estado           string            `json:"estado"`
	ResultadosModelo *ResultadosModelo `json:"resultadosModelo"`
	FechaSubida      string            `json:"fechaSubida"`
}

type Query struct {
}

type ResultadosModelo struct {
	ProbNeumonia       float64 `json:"probNeumonia"`
	Etiqueta           string  `json:"etiqueta"`
	FechaProcesamiento string  `json:"fechaProcesamiento"`
}
