// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PreDiagnostic struct {
	PrediagnosticID  string            `json:"prediagnostic_id"`
	PacienteID       string            `json:"pacienteId"`
	Urlrad           string            `json:"urlrad"`
	Estado           string            `json:"estado"`
	ResultadosModelo *ResultadosModelo `json:"resultadosModelo"`
	FechaSubida      string            `json:"fechaSubida"`
}

type Query struct {
}

type ResultadosModelo struct {
	ProbNeumonia       float64 `json:"probNeumonia"`
	Etiqueta           string  `json:"etiqueta"`
	FechaProcesamiento string  `json:"fechaProcesamiento"`
}
